server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:8000"
              - "http://localhost:56857"
              allowedHeaders: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: ventas-service
          uri: lb://ventas-service
          predicates:
            - Path=/categoria/**,/subcategoria/**,/producto/**,/cliente/**,/voucher/**,/voucher_detalle/**,/empresa/**,/entrega/**,/imagen**    
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

   

